# Generated by Django 3.0 on 2021-05-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0002_myorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idgen',
            field=models.TextField(null=True),
        ),
    ]
