# Generated by Django 3.0 on 2021-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0003_user_idgen'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegpro',
            name='market_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
