# Generated by Django 3.2.1 on 2021-05-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0005_auto_20210526_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(choices=[('product quality issues', 'product quality issues'), ('I want to change address/phone number', 'I want to change address/phone number'), ('I have purchased product somewhere else', 'I have purchased product somewhere else'), ('others', 'others')], max_length=200, null=True),
        ),
    ]
