# Generated by Django 3.2.1 on 2021-05-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarMeKart', '0006_alter_myorders_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myorders',
            name='cancel',
            field=models.CharField(max_length=200),
        ),
    ]
